import type { KnownMaterials } from "./combo";
import { MAX_STAMINA_UNITS, REGEN_MINUTES_PER_UNIT, STORAGE_KEY } from "./config";
import { SEED_OPTIONS } from "./data/options";
import type { GameEvent, Localized } from "./types";

export interface GameState {
  /** UI + generated-content language. Defaults to "zh"; main.ts overrides
   * this from navigator.language only the very first time a player ever
   * loads the app (see hasSavedState below) — state.ts itself has no access
   * to the browser global and shouldn't reach for one. */
  language: "zh" | "en";
  staminaUnits: number;
  staminaLastSettled: number; // epoch ms — last time we converted elapsed real time into units
  unlockedOptionIds: string[];
  collectedComboKeys: string[]; // discovery order, unique
  eventsByCombo: Record<string, GameEvent>;
  /** When *this* player first personally saw each combo — distinct from the
   * event's own `discoveredAt`, which is when it was first ever generated by
   * anyone. Keyed by comboKey, one entry per collected combo. */
  personalDiscoveredAt: Record<string, number>;
  /** Chosen display name ("入職名稱") — shown in the header regardless of
   * login state, and sent as the discovererName on newly generated events.
   * Empty string means "not set yet", which the UI treats as required input. */
  playerName: string;
  /** Label/category/description/discovery-info for every AI-invented
   * material this player has ever unlocked, keyed by id — there's no fixed
   * catalog to look these up in (see functions/src/index.ts), so once
   * discovered they're remembered here for rendering pills, decoding
   * comboKeys, and the 歷史 tab's 要素 sub-tab. Populated by recordEvent from
   * each event's featuredOption. */
  knownMaterials: KnownMaterials;
  /** Whether the one-time gameplay tutorial has been shown — fires once,
   * right after the player sets their 入職名稱 for the very first time. */
  hasSeenTutorial: boolean;
  /** Read-only mirror of the player's ECPay top-up wallet
   * (players/{uid}.paidCoinBalance/.potions in Firestore). Only Cloud
   * Functions ever change the real balance/inventory — this local copy
   * exists purely for display and is refreshed from cloudSync's
   * pullRemoteState; nothing in this file mutates it, and pushRemoteState
   * must never send it back to the server (see cloudSync.ts's
   * toSyncedProfile). `potions` is keyed by productId — how many of that
   * potion this player currently owns, unused/unspent. */
  wallet: { paidCoinBalance: number; potions: Record<string, number> };
  /** Epoch ms of when the player confirmed the top-up terms/consent modal —
   * null means never. Shown once (gates the first purchase), not required
   * again on every later purchase; the market page keeps a "查看條款" link
   * to reopen the same modal read-only at any time. */
  consentAcceptedAt: number | null;
  /** id of the last admin announcement (see src/types.ts's Announcement)
   * this player permanently dismissed via "不再顯示" — null means none.
   * Only meaningful for a `dismissible` announcement; a non-dismissible one
   * always shows regardless of this value. */
  dismissedAnnouncementId: string | null;
  /** Current 職稱 (job title) — starts at DEFAULT_JOB_TITLE, moves forward
   * only when a generated event's `newJobTitle` says so (see
   * eventEngine.ts's resolveAction and functions/src/index.ts's buildPrompt).
   * Covers both promotion within the same job (新進員工→主管→CEO) and a
   * switch to a different job entirely — the game treats both as the same
   * kind of change. Baked into every new event's comboKey, so the same
   * materials tell a different story depending on this. */
  jobTitle: Localized;
}

/** Every player starts here — a blank-slate office worker with nothing
 * decided yet. Exported so cloudSync.ts can fall back to the same value for
 * a pre-existing remote profile that predates this field. */
export const DEFAULT_JOB_TITLE: Localized = { zh: "新進員工", en: "New Employee" };

/** Whether a save already exists — checked *before* loadState() so the
 * caller (main.ts) knows whether to run first-visit navigator.language
 * detection, since loadState() collapses "no save" and "corrupt save" into
 * the same freshState() result and doesn't distinguish them to its caller. */
export function hasSavedState(): boolean {
  return localStorage.getItem(STORAGE_KEY) !== null;
}

function freshState(): GameState {
  return {
    language: "zh",
    staminaUnits: MAX_STAMINA_UNITS,
    staminaLastSettled: Date.now(),
    unlockedOptionIds: SEED_OPTIONS.map((o) => o.id),
    collectedComboKeys: [],
    eventsByCombo: {},
    personalDiscoveredAt: {},
    playerName: "",
    knownMaterials: {},
    hasSeenTutorial: false,
    wallet: { paidCoinBalance: 0, potions: {} },
    consentAcceptedAt: null,
    dismissedAnnouncementId: null,
    jobTitle: DEFAULT_JOB_TITLE,
  };
}

export function loadState(): GameState {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return freshState();
  try {
    const parsed = JSON.parse(raw) as GameState;
    if (
      typeof parsed.staminaUnits !== "number" ||
      typeof parsed.staminaLastSettled !== "number" ||
      !Array.isArray(parsed.unlockedOptionIds) ||
      !Array.isArray(parsed.collectedComboKeys) ||
      typeof parsed.eventsByCombo !== "object"
    ) {
      return freshState();
    }
    // Older saves predate personalDiscoveredAt — default it rather than
    // wiping otherwise-valid progress just because of a schema addition.
    if (typeof parsed.personalDiscoveredAt !== "object" || parsed.personalDiscoveredAt === null) {
      parsed.personalDiscoveredAt = {};
    }
    if (typeof parsed.playerName !== "string") {
      parsed.playerName = "";
    }
    if (typeof parsed.knownMaterials !== "object" || parsed.knownMaterials === null) {
      parsed.knownMaterials = {};
    }
    // Older saves predate the tutorial — default to "already seen" so
    // existing players don't suddenly get it on their next visit; only a
    // genuinely fresh save (no playerName yet) should ever show it.
    if (typeof parsed.hasSeenTutorial !== "boolean") {
      parsed.hasSeenTutorial = true;
    }
    // Older saves predate language selection — default to "zh", since that's
    // the only language the app ever spoke while they were playing. Only a
    // genuinely first-ever visit (no save at all) gets navigator-detected.
    if (parsed.language !== "zh" && parsed.language !== "en") {
      parsed.language = "zh";
    }
    // Older saves predate the top-up wallet — default to zero rather than
    // wiping otherwise-valid progress. A real balance (if any) is restored
    // moments later for Google-linked players via cloudSync's pullRemoteState.
    if (typeof parsed.wallet !== "object" || parsed.wallet === null) {
      parsed.wallet = { paidCoinBalance: 0, potions: {} };
    }
    // Older saves predate the potion inventory — default to none rather
    // than wiping otherwise-valid progress. A real inventory (if any) is
    // restored moments later for Google-linked players via pullRemoteState.
    if (typeof parsed.wallet.potions !== "object" || parsed.wallet.potions === null) {
      parsed.wallet.potions = {};
    }
    // Older saves predate the consent modal — default to "never accepted"
    // so returning players still see it once before their first purchase.
    if (typeof parsed.consentAcceptedAt !== "number") {
      parsed.consentAcceptedAt = null;
    }
    // Older saves predate the announcement system — default to "nothing
    // dismissed yet", which just means the next active announcement (if
    // any) will show once, same as for a brand-new player.
    if (typeof parsed.dismissedAnnouncementId !== "string") {
      parsed.dismissedAnnouncementId = null;
    }
    // Older saves predate the job-title system — default to the same
    // starting title a brand-new player gets, rather than wiping progress.
    if (typeof parsed.jobTitle !== "object" || parsed.jobTitle === null || typeof parsed.jobTitle.zh !== "string") {
      parsed.jobTitle = DEFAULT_JOB_TITLE;
    }
    // Defensive clamp: a save from before MAX_STAMINA_UNITS was lowered
    // could otherwise show e.g. "144 / 48".
    parsed.staminaUnits = Math.min(parsed.staminaUnits, MAX_STAMINA_UNITS);
    return parsed;
  } catch {
    return freshState();
  }
}

export function saveState(state: GameState): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}

/** Converts elapsed real-world time into regenerated stamina units, in place. */
export function settleStamina(state: GameState): GameState {
  if (state.staminaUnits >= MAX_STAMINA_UNITS) {
    state.staminaLastSettled = Date.now();
    return state;
  }
  const elapsedMs = Date.now() - state.staminaLastSettled;
  const elapsedMinutes = elapsedMs / 60_000;
  const regeneratedUnits = Math.floor(elapsedMinutes / REGEN_MINUTES_PER_UNIT);
  if (regeneratedUnits <= 0) return state;

  const newUnits = Math.min(MAX_STAMINA_UNITS, state.staminaUnits + regeneratedUnits);
  const unitsActuallyApplied = newUnits - state.staminaUnits;
  state.staminaUnits = newUnits;
  // Only advance the settlement clock by the time we actually consumed, so leftover
  // fractional minutes aren't lost (important once stamina is near the cap).
  state.staminaLastSettled += unitsActuallyApplied * REGEN_MINUTES_PER_UNIT * 60_000;
  return state;
}


export function spendStamina(state: GameState, units: number): boolean {
  if (units <= 0 || units > state.staminaUnits) return false;
  state.staminaUnits -= units;
  return true;
}

export function isUnlocked(state: GameState, optionId: string): boolean {
  return state.unlockedOptionIds.includes(optionId);
}

export function unlockOption(state: GameState, optionId: string): boolean {
  if (isUnlocked(state, optionId)) return false;
  state.unlockedOptionIds.push(optionId);
  return true;
}

export function recordEvent(state: GameState, event: GameEvent): { isNewDiscovery: boolean } {
  const isNewDiscovery = !(event.comboKey in state.eventsByCombo);
  state.eventsByCombo[event.comboKey] = event;
  if (isNewDiscovery) {
    state.collectedComboKeys.push(event.comboKey);
    state.personalDiscoveredAt[event.comboKey] = Date.now();
  }
  // The `.label` check (not just optionId presence) matters: events cached
  // before the AI-invention rearchitecture only ever stored {category,
  // optionId} — recording one of those without this guard would poison
  // knownMaterials with a label-less entry that then permanently shadows
  // combo.ts's legacy-table fallback for that id.
  if (event.featuredOption?.label?.zh && !(event.featuredOption.optionId in state.knownMaterials)) {
    state.knownMaterials[event.featuredOption.optionId] = {
      category: event.featuredOption.category,
      label: event.featuredOption.label,
      description: event.featuredOption.description,
      discovererName: event.discovererName,
      discoveredAt: event.discoveredAt,
      comboKey: event.comboKey,
      durationUnits: event.durationUnits,
    };
  }
  return { isNewDiscovery };
}
